name: Delete merged branch (with exclusions)

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-branch:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete merged branch
        uses: ./.github/actions/delete-merged-branch
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
